import { getRepoClassCached } from './commitAttribution.js'
import { getGlobalConfig } from './config.js'
import { isEnvTruthy } from './envUtils.js'
import { getSettingsForSource } from './settings/settings.js'

export type PublicModeValue = 'on' | 'off' | 'auto'

export type PublicModeResolution = {
  enabled: boolean
  mode: PublicModeValue
  source: 'env' | 'localSettings' | 'userSettings' | 'default'
  repoClass: 'internal' | 'external' | 'none' | 'unknown'
}

function parsePublicModeEnvValue(
  rawValue: string | undefined,
): PublicModeValue | undefined {
  const normalized = rawValue?.trim().toLowerCase()
  if (
    normalized === 'on' ||
    normalized === 'off' ||
    normalized === 'auto'
  ) {
    return normalized
  }
  return undefined
}

function getRepoClassification(): PublicModeResolution['repoClass'] {
  return getRepoClassCached() ?? 'unknown'
}

function isAutoPublicModeEnabled(
  repoClass: PublicModeResolution['repoClass'],
): boolean {
  return repoClass !== 'internal'
}

export function resolvePublicModeState(): PublicModeResolution {
  const envMode = parsePublicModeEnvValue(process.env.CLAUDE_CODE_PUBLIC_MODE)
  if (envMode) {
    const repoClass = getRepoClassification()
    return {
      enabled:
        envMode === 'on'
          ? true
          : envMode === 'off'
            ? false
            : isAutoPublicModeEnabled(repoClass),
      mode: envMode,
      source: 'env',
      repoClass,
    }
  }

  if (isEnvTruthy(process.env.CLAUDE_CODE_UNDERCOVER)) {
    return {
      enabled: true,
      mode: 'on',
      source: 'env',
      repoClass: getRepoClassification(),
    }
  }

  const localMode = getSettingsForSource('localSettings')?.publicMode
  if (localMode) {
    const repoClass = getRepoClassification()
    return {
      enabled:
        localMode === 'on'
          ? true
          : localMode === 'off'
            ? false
            : isAutoPublicModeEnabled(repoClass),
      mode: localMode,
      source: 'localSettings',
      repoClass,
    }
  }

  const userDefault = getSettingsForSource('userSettings')?.defaultPublicMode
  if (userDefault) {
    const repoClass = getRepoClassification()
    return {
      enabled:
        userDefault === 'on'
          ? true
          : userDefault === 'off'
            ? false
            : isAutoPublicModeEnabled(repoClass),
      mode: userDefault,
      source: 'userSettings',
      repoClass,
    }
  }

  const repoClass = getRepoClassification()
  return {
    enabled: isAutoPublicModeEnabled(repoClass),
    mode: 'auto',
    source: 'default',
    repoClass,
  }
}

export function isPublicModeEnabled(): boolean {
  return resolvePublicModeState().enabled
}

export function getPublicModeInstructions(): string {
  return `## PUBLIC MODE — PUBLIC-FACING WRITING GUARD

Treat commit messages, PR titles, PR bodies, changelog entries, and issue
comments as public-facing text.

Do not include:
- AI attribution or "generated by AI" phrasing
- Model names, version numbers, or provider names
- Internal repository names, internal tools, internal links, or internal channels
- Claims about hidden internal context or private systems

Write as a human developer would:
- describe the code change and why it matters
- keep the language natural and reviewable
- focus on the software outcome, not the tool used to produce it`
}

export function shouldShowPublicModeAutoNotice(): boolean {
  const resolution = resolvePublicModeState()
  if (!resolution.enabled || resolution.mode !== 'auto') {
    return false
  }

  if (
    resolution.source === 'env' &&
    (parsePublicModeEnvValue(process.env.CLAUDE_CODE_PUBLIC_MODE) === 'auto' ||
      isEnvTruthy(process.env.CLAUDE_CODE_UNDERCOVER))
  ) {
    return false
  }

  return !getGlobalConfig().hasSeenUndercoverAutoNotice
}
